# Generated by Django 4.2.7 on 2025-08-22 06:40

import claims.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(editable=False, max_length=7)),
                ('date_of_admission', models.DateField()),
                ('date_of_discharge', models.DateField()),
                ('query_reply_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('tpa_name', models.CharField(max_length=200)),
                ('parent_insurance', models.CharField(max_length=200)),
                ('claim_id', models.CharField(max_length=100, unique=True)),
                ('uhid_ip_no', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=200)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('mou_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('co_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('consumable_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hospital_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('paid_by_patient', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hospital_discount_authority', models.CharField(blank=True, max_length=200)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tds', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_settled_in_ac', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('difference_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('reason_less_settlement', models.TextField(blank=True)),
                ('approval_letter', models.FileField(blank=True, null=True, upload_to=claims.models.claim_file_upload_path)),
                ('physical_file_dispatch', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('not_required', 'Not Required')], default='pending', max_length=20)),
                ('physical_file_upload', models.FileField(blank=True, null=True, upload_to=claims.models.claim_file_upload_path)),
                ('query_on_claim', models.FileField(blank=True, null=True, upload_to=claims.models.claim_file_upload_path)),
                ('claim_settled_software', models.BooleanField(default=False)),
                ('receipt_verified_bank', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['claim_id'], name='claims_clai_claim_i_faa3f4_idx'), models.Index(fields=['patient_name'], name='claims_clai_patient_f7d363_idx'), models.Index(fields=['month'], name='claims_clai_month_4d4c1c_idx'), models.Index(fields=['tpa_name'], name='claims_clai_tpa_nam_c69898_idx'), models.Index(fields=['settlement_date'], name='claims_clai_settlem_633191_idx')],
            },
        ),
    ]
