# Generated by Django 4.2.7 on 2025-08-23 07:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='date_of_discharge',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='parent_insurance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='claim',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='claim',
            name='tpa_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='claim',
            name='uhid_ip_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
