# Generated by Django 4.2.7 on 2025-08-26 14:33

import claims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_approved_amount_alter_claim_bill_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='query_reply_upload',
            field=models.FileField(blank=True, null=True, upload_to=claims.models.claim_file_upload_path),
        ),
    ]
