# Generated by Django 4.2.7 on 2025-08-26 15:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claim_query_reply_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='amount_settled_in_ac',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='total_settled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
