# Generated by Django 4.2.7 on 2025-08-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_claim_amount_settled_in_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='utr_number',
            field=models.CharField(blank=True, help_text='Unique Transaction Reference Number', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['utr_number'], name='claims_clai_utr_num_1e8738_idx'),
        ),
    ]
