# Generated by Django 4.2.7 on 2025-08-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_claim_utr_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='month',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True),
        ),
    ]
