# Generated by Django 4.2.7 on 2025-08-29 17:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_alter_claim_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='amount_settled_in_ac',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='co_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='consumable_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='hospital_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='mou_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='other_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='paid_by_patient',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='tds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='total_settled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
