# Generated by Django 4.2.7 on 2025-09-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_alter_claim_amount_settled_in_ac_alter_claim_co_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='approval_letter',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='physical_file_upload',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='query_on_claim',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='query_reply_upload',
        ),
        migrations.AddField(
            model_name='claim',
            name='approval_letter_uploaded',
            field=models.BooleanField(default=False, verbose_name='Approval Letter Uploaded'),
        ),
        migrations.AddField(
            model_name='claim',
            name='physical_file_uploaded',
            field=models.BooleanField(default=False, verbose_name='Physical File Uploaded'),
        ),
        migrations.AddField(
            model_name='claim',
            name='query_on_claim_uploaded',
            field=models.BooleanField(default=False, verbose_name='Query on Claim Uploaded'),
        ),
        migrations.AddField(
            model_name='claim',
            name='query_reply_uploaded',
            field=models.BooleanField(default=False, verbose_name='Query Reply Uploaded'),
        ),
    ]
